---
  - name: upload tar.gz Kibana from remote URL
    get_url:
      url: "https://artifacts.elastic.co/downloads/kibana/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
      dest: "/tmp/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
      mode: 755
    register: get_kibana
    until: get_kibana is succeeded
  - name: Create directory for Kibana
    file:
      state: directory
      path: "{{ kibana_home }}"
  - name: Extract Kibana to home directory
    unarchive:
      copy: false
      src: "/tmp/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
      dest: "{{ kibana_home }}"
      extra_opts: [ --strip-components=1 ]
      creates: "{{ kibana_home }}/bin/kibana"
  - name: Set environment Kibana
    #become: yes
    template:
      src: templates/kib.sh.j2
      dest: /etc/profile.d/kib.sh